### ISSUE TITLE
在调试官方例程的时候调试报错了，应该怎么改？

### ISSUE THREAD

**Issue by TongTongHou4876** [limuloo/PyDIff#20]
2024-08-13 23:20:34,688 INFO: Dataset [LOL_Dataset] - train is built.
num_iter_per_epoch=0
total_iters=500000
Traceback (most recent call last):
  File "PyDiff/pydiff/train.py", line 12, in <module>
    train_pipeline(root_path)
  File "/home/htt/Documents/PyDIff/BasicSR-light/basicsr/train.py", line 135, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "/home/htt/Documents/PyDIff/BasicSR-light/basicsr/train.py", line 63, in create_train_val_dataloader
    total_epochs = math.ceil(total_iters / (num_iter_per_epoch))
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/home/htt/anaconda3/envs/PyDiff/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/htt/anaconda3/envs/PyDiff/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/htt/anaconda3/envs/PyDiff/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/htt/anaconda3/envs/PyDiff/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/htt/anaconda3/envs/PyDiff/bin/python', '-u', 'PyDiff/pydiff/train.py', '--local_rank=0', '-opt', 'PyDiff/options/train_v2.yaml', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by limuloo** [comment]
@TongTongHou4876  这看起来是你的数据集路径没弄对
